package org.ozmi.aroundsee.server.services;

public enum PlacesTypes {
	accounting,
	airport,
	amusement_park,
	aquarium,
	art_gallery,
	atm,
	bakery,
	bank,
	bar,
	beauty_salon,
	bicycle_store,
	book_store,
	bowling_alley,
	bus_station,
	cafe,
	campground,
	car_dealer,
	car_rental,
	car_repair,
	car_wash,
	casino,
	cemetery,
	church,
	city_hall,
	clothing_store,
	convenience_store,
	courthouse,
	dentist,
	department_store,
	doctor,
	electrician,
	electronics_store,
	embassy,
	fire_station,
	florist,
	funeral_home,
	furniture_store,
	gas_station,
	gym,
	hair_care,
	hardware_store,
	hindu_temple,
	home_goods_store,
	hospital,
	insurance_agency,
	jewelry_store,
	laundry,
	lawyer,
	library,
	liquor_store,
	local_government_office,
	locksmith,
	lodging,
	meal_delivery,
	meal_takeaway,
	mosque,
	movie_rental,
	movie_theater,
	moving_company,
	museum,
	night_club,
	painter,
	park,
	parking,
	pet_store,
	pharmacy,
	physiotherapist,
	plumber,
	police,
	post_office,
	real_estate_agency,
	restaurant,
	roofing_contractor,
	rv_park,
	school,
	shoe_store,
	shopping_mall,
	spa,
	stadium,
	storage,
	store,
	subway_station,
	synagogue,
	taxi_stand,
	train_station,
	transit_station,
	travel_agency,
	university,
	veterinary_care,
	zoo
//	ACCOUNTING,
//	AIRPORT,
//	AMUSEMENT_PARK,
//	AQUARIUM,
//	ART_GALLERY,
//	ATM,
//	BAKERY,
//	BANK,
//	BAR,
//	BEAUTY_SALON,
//	BICYCLE_STORE,
//	BOOK_STORE,
//	BOWLING_ALLEY,
//	BUS_STATION,
//	CAFE,
//	CAMPGROUND,
//	CAR_DEALER,
//	CAR_RENTAL,
//	CAR_REPAIR,
//	CAR_WASH,
//	CASINO,
//	CEMETERY,
//	CHURCH,
//	CITY_HALL,
//	CLOTHING_STORE,
//	CONVENIENCE_STORE,
//	COURTHOUSE,
//	DENTIST,
//	DEPARTMENT_STORE,
//	DOCTOR,
//	ELECTRICIAN,
//	ELECTRONICS_STORE,
//	EMBASSY,
//	FIRE_STATION,
//	FLORIST,
//	FUNERAL_HOME,
//	FURNITURE_STORE,
//	GAS_STATION,
//	GYM,
//	HAIR_CARE,
//	HARDWARE_STORE,
//	HINDU_TEMPLE,
//	HOME_GOODS_STORE,
//	HOSPITAL,
//	INSURANCE_AGENCY,
//	JEWELRY_STORE,
//	LAUNDRY,
//	LAWYER,
//	LIBRARY,
//	LIQUOR_STORE,
//	LOCAL_GOVERNMENT_OFFICE,
//	LOCKSMITH,
//	LODGING,
//	MEAL_DELIVERY,
//	MEAL_TAKEAWAY,
//	MOSQUE,
//	MOVIE_RENTAL,
//	MOVIE_THEATER,
//	MOVING_COMPANY,
//	MUSEUM,
//	NIGHT_CLUB,
//	PAINTER,
//	PARK,
//	PARKING,
//	PET_STORE,
//	PHARMACY,
//	PHYSIOTHERAPIST,
//	PLUMBER,
//	POLICE,
//	POST_OFFICE,
//	REAL_ESTATE_AGENCY,
//	RESTAURANT,
//	ROOFING_CONTRACTOR,
//	RV_PARK,
//	SCHOOL,
//	SHOE_STORE,
//	SHOPPING_MALL,
//	SPA,
//	STADIUM,
//	STORAGE,
//	STORE,
//	SUBWAY_STATION,
//	SYNAGOGUE,
//	TAXI_STAND,
//	TRAIN_STATION,
//	TRANSIT_STATION,
//	TRAVEL_AGENCY,
//	UNIVERSITY,
//	VETERINARY_CARE,
//	ZOO
}